# 2024-09-25: ubuntu-latest = ubuntu-22.04
# See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
name: "Meson: clang"

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        # Prevent blocking apt install on a question during configuring of tzdata.
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install libxml2-dev libxml2-utils docbook5-xml docbook-xsl libglibmm-2.68-dev mm-common clang meson ninja-build python3-setuptools --yes
        export CC=clang
        export CXX=clang++
        meson setup -Dwarnings=fatal -Dwarning_level=3 -Dwerror=true _build
        cd _build
        meson compile
    - name: Test
      run: |
        cd _build
        meson test
    - name: Dist
      run: |
        sudo apt install git --yes
        # dist runs setup again so we need to specify CC and CXX again.
        export CC=clang
        export CXX=clang++
        cd _build
        meson dist
